version: "2.3"

services:
  db: # by default, expose 3306 port
    image: mariadb:latest
    restart: always
    volumes:
      - ./vide_frigo/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vide_frigo
    ports:
      - "3316:3306"
  peuplement: 
    build: ./vide_frigo/initdb/peuplement_BD
    image: vfrigo:peuplement
    volumes: 
      - ./vide_frigo/initdb/peuplement_BD:/peuplement_BD
      - peuplement_BD/target
    ports:
      - "4567:4567"
    depends_on:
      - db
    init: true
  server:
    build: ./vide_frigo
    image: vfrigo:vide_frigo
    volumes:
      - ./vide_frigo:/home/node/app
      - /home/node/app/node_modules
    environment:
      - NODE_ENV=development
      - DB_SERVER_HOST=db
      - NODE_PORT=3000
      - DB_SERVER_PORT=3306
      - DB_SERVER_USER=root
      - DB_SERVER_PASSWORD=root
      - DB_NAME=vide_frigo
    ports:
      - "3000:3000"
      - "4200:4200"
    depends_on:
      - db
    init: true
